# Generated by Django 3.2.2 on 2021-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=60)),
                ('doctor_phone', models.CharField(max_length=12)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='1', max_length=60)),
                ('doctor_description', models.CharField(max_length=120)),
            ],
        ),
    ]
