# Generated by Django 3.2.8 on 2021-10-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patience_diseases', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatiencePicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('picture_title', models.CharField(max_length=60)),
                ('picture_description', models.CharField(max_length=120)),
                ('taken_date', models.DateTimeField(auto_now_add=True)),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patience_diseases.patiencedisease')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patiences.patience')),
            ],
        ),
    ]
