# Generated by Django 3.2.2 on 2021-10-29 18:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patience_pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiencepicture',
            name='picture_link',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
