# Generated by Django 3.2.8 on 2021-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patience_name', models.CharField(max_length=60)),
                ('patience_gender', models.CharField(max_length=60)),
                ('patience_age', models.IntegerField()),
                ('patience_address', models.CharField(max_length=60)),
                ('patience_phone', models.CharField(max_length=60)),
                ('patience_email', models.EmailField(max_length=254)),
                ('opt', models.CharField(max_length=120)),
            ],
        ),
    ]
