# Generated by Django 3.2.2 on 2021-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patience_name', models.CharField(max_length=60)),
                ('patience_gender', models.CharField(default='', max_length=60)),
                ('patience_weight', models.CharField(default='', max_length=60)),
                ('patience_height', models.CharField(default='', max_length=60)),
                ('patience_age', models.IntegerField()),
                ('patience_disease', models.CharField(default='', max_length=60)),
                ('patience_address', models.CharField(max_length=60)),
                ('patience_phone', models.CharField(max_length=60)),
                ('patience_email', models.EmailField(max_length=254)),
                ('patience_insurance', models.CharField(default='', max_length=60)),
                ('opt', models.CharField(default='XB3zNDyKKoAE9Au8HBgWBtBQLyhetazvvFDsRLzotFcBQS6vSvRTDrDKuQGT', max_length=60)),
            ],
        ),
    ]
